steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest',
      '.'
    ]

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest'
    ]

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y curl

        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh
        mv ./bin/grype /usr/local/bin/

        grype asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest -o json > result.json

  # Upload result
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp','result.json','gs://darp-grype-bucket-123/']

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
