steps:

# Pull image
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'caddy']

# Authenticate Docker with Artifact Registry
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'configure-docker', 'asia-south1-docker.pkg.dev']

# Tag image
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag','caddy','asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest']

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update
      apt-get install -y curl

      curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh
      mv ./bin/grype /usr/local/bin/

      grype asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest -o json > result-$BUILD_ID.json

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest']

# Upload scan result to bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','result-$BUILD_ID.json','gs://darp-grype-bucket-123/']

# ✅ FIX FOR YOUR ERROR
options:
  logging: CLOUD_LOGGING_ONLY
