steps:

# 🔨 Build Docker image from your repo
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'caddy-app', '.']

# 🔐 Authenticate Docker
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'configure-docker', 'asia-south1-docker.pkg.dev']

# 🏷️ Tag image
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'caddy-app', 'asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest']

# 📦 Convert image to tar (IMPORTANT)
- name: 'gcr.io/cloud-builders/docker'
  args: ['save', 'caddy-app', '-o', 'image.tar']

# 🔍 Scan BEFORE push (SAFE)
- name: 'anchore/grype'
  args: ['/workspace/image.tar', '-o', 'table', '--file', 'result-$BUILD_ID.txt']

# 🚀 Push image (after scan)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/caddy-repo/caddy-app:latest']

# ☁️ Upload result
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'result-$BUILD_ID.txt', 'gs://darp-grype-bucket-123/']

options:
  logging: CLOUD_LOGGING_ONLY
